services:
  minecraft:
    build:
      context: .
      args:
        EULA: true
    image: docker.io/siisise/mc:1.21
    volumes:
      - minecraft-world:/opt/app/world
    ports:
      - '25565:25565'
volumes:
  minecraft-world:
